/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ez.view;

import com.ez.amember.model.amemberDAO;
import com.ez.amember.model.amemberDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HYOKKER
 */
public class amemberFrame extends javax.swing.JFrame implements ActionListener{
    private LoginGUI loginGui;
    private amemberDAO amemberDao;
    private boolean duplicateChecked;  //중복확인 했으면 true
    private int amemberFlag;  //회원가입인지, 수정인지 구분해주는 값
    
    public static final int AMEMBER_REGISTER=1;  //회원가입
    public static final int AMEMBER_EDIT=2;      //회원정보 수정
    private String[] emailArr={"naver.com", "nate.com","daum.net","gmail.com","직접입력"};
    /**
     * Creates new form amemberFrame
     */
    public amemberFrame() {
        initComponents();
        init();
        addEvent();
    }
        public amemberFrame(int amemberFlag){
        this();
        
        this.amemberFlag=amemberFlag;
        amemberProc();
    }
    
    public amemberFrame(LoginGUI loginGui, int amemberFlag){
        this();
        
        this.loginGui=loginGui;
        this.amemberFlag=amemberFlag;
        amemberProc();
    }
    
    
    public boolean isDuplicateChecked() {
        return duplicateChecked;
    }
    
    public void setDuplicateChecked(boolean duplicateChecked) {
        this.duplicateChecked = duplicateChecked;
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfPwd = new javax.swing.JPasswordField();
        tfuserid = new javax.swing.JTextField();
        cbhp1 = new javax.swing.JComboBox<>();
        tfhp2 = new javax.swing.JTextField();
        tfhp3 = new javax.swing.JTextField();
        tfemail1 = new javax.swing.JTextField();
        cbemail2 = new javax.swing.JComboBox<>();
        tfemail3 = new javax.swing.JTextField();
        tfZipcode = new javax.swing.JTextField();
        btZipcode = new javax.swing.JButton();
        tfaddress1 = new javax.swing.JTextField();
        tfaddress2 = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();
        btCancle = new javax.swing.JButton();
        btDup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("회원 가입"));

        jLabel1.setText("아이디");

        jLabel2.setText("비밀번호");

        jLabel3.setText("이름");

        jLabel4.setText("전화번호");

        jLabel5.setText("이메일");

        jLabel6.setText("우편번호");

        jLabel7.setText("@");

        jLabel8.setText("주소");

        jLabel9.setText("상세주소");

        tfPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPwdActionPerformed(evt);
            }
        });

        cbhp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "010", "011", "016", "017" }));
        cbhp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhp1ActionPerformed(evt);
            }
        });

        cbemail2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "naver.com", "nate.com", "daum.net", "직접 입력" }));

        btZipcode.setText("우편변호 찾기");

        tfaddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaddress2ActionPerformed(evt);
            }
        });

        btRegister.setText("회원가입");

        btCancle.setText("취 소");

        btDup.setText("중복 확인");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfName)
                            .addComponent(tfPwd)
                            .addComponent(tfuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btRegister)
                                .addGap(48, 48, 48)
                                .addComponent(btCancle))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfaddress2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(tfaddress1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbemail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbhp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfhp2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btDup)
                                            .addComponent(tfhp3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(tfemail3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btZipcode)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btDup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbhp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfhp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfhp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbemail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfemail3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btZipcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfaddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegister)
                    .addComponent(btCancle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfaddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaddress2ActionPerformed

    private void tfPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPwdActionPerformed

    private void cbhp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbhp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amemberFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancle;
    private javax.swing.JButton btDup;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton btZipcode;
    private javax.swing.JComboBox<String> cbemail2;
    private javax.swing.JComboBox<String> cbhp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPwd;
    public javax.swing.JTextField tfZipcode;
    public javax.swing.JTextField tfaddress1;
    private javax.swing.JTextField tfaddress2;
    private javax.swing.JTextField tfemail1;
    private javax.swing.JTextField tfemail3;
    private javax.swing.JTextField tfhp2;
    private javax.swing.JTextField tfhp3;
    public javax.swing.JTextField tfuserid;
    // End of variables declaration//GEN-END:variables

    private void init() {
        amemberDao = new amemberDAO();
        
        cbhp1.removeAllItems();
        cbhp1.addItem("010");
        cbhp1.addItem("011");
        cbhp1.addItem("016");
        cbhp1.addItem("017");
        cbhp1.addItem("019");
        
        DefaultComboBoxModel cmodel=new DefaultComboBoxModel(emailArr);
        cbemail2.setModel(cmodel);
        
        tfemail3.setEnabled(false);
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void addEvent() {
        btRegister.addActionListener(this);
        btDup.addActionListener(this);
        btZipcode.addActionListener(this);
        btCancle.addActionListener(this);
    }

    private void amemberProc() {
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btRegister){
            try {
                if(amemberFlag==AMEMBER_REGISTER){
                    //회원가입 처리
                    register();
                }else if(amemberFlag==AMEMBER_EDIT){
                //회원수정 처리
                    amemEdit();
                }
            } catch (SQLException ex) {
                    Logger.getLogger(amemberFrame.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        }else if (e.getSource()==btDup){
            dupuserid f = new dupuserid(this, tfuserid.getText());
            f.setVisible(true);
        }else if (e.getSource()==btZipcode){
            subAddress f = new subAddress();
            f.setVisible(true);
        }else if (e.getSource()==btCancle){
            dispose();
        }
    }
    
    public void register() throws SQLException{
        //1
        String userid = tfuserid.getText();
        String name = tfName.getText();
        String pwd = tfPwd.getText();
        String address1 = tfaddress1.getText();
        String address2 = tfaddress2.getText();
        String zipcode = tfZipcode.getText();
        String hp1 =(String) cbhp1.getSelectedItem();
        String hp2 = tfhp2.getText();
        String hp3 = tfhp3.getText();
        String email1 = tfemail1.getText();
        String email2 =(String) cbemail2.getSelectedItem();
        String email3 = tfemail3.getText();
        
        if(name==null || name.isEmpty()){
            JOptionPane.showMessageDialog(this, "이름 입력하세요");
            tfName.requestFocus();
            return;
        }
        if(userid==null || userid.isEmpty()){
            JOptionPane.showMessageDialog(this, "아이디 입력하세요");
            tfuserid.requestFocus();
            return;
        }
        if(pwd==null || pwd.isEmpty()){
            JOptionPane.showMessageDialog(this, "비밀번호 입력하세요");
            tfPwd.requestFocus();
            return;
        }
        
        if(!duplicateChecked){
            JOptionPane.showMessageDialog(this, "ID 중복확인하세요");
            btDup.requestFocus();
            return;
        }
        
        amemberDTO dto = new amemberDTO();
        dto.setUserid(userid);
        dto.setCname(name);
        dto.setPwd(pwd);
        dto.setZipcode(zipcode);
        dto.setAddress1(address1);
        dto.setAddress2(address2);
        dto.setCoupon("없음");
        
        
        //휴대폰처리
        String hp="", email="";
        if(hp2!=null && !hp2.isEmpty() && hp3!=null && !hp3.isEmpty()){
            hp=hp1+"-"+hp2+"-"+hp3;
        }
        
        //이메일 처리
        if(email1!=null && !email1.isEmpty()){
            if(email2.equals("직접입력")){
                if(email3!=null && !email3.isEmpty()){
                    email=email1+"@"+email3;
                }
            }else{
                email=email1+"@"+email2;
            }
        }
        dto.setTel(hp);
        dto.setEmail(email);
        
        int cnt = amemberDao.insertAmember(dto);
        String msg="";
        if(cnt>0){
            msg="회원가입되었습니다";
            loginGui.tfuserid.setText(userid);
            
            this.dispose();
        }else{
            msg="회원가입 실패";
        }
        JOptionPane.showMessageDialog(this, msg);
    }

    private void amemEdit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
